# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dev/dub_rt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dev/dub_rt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dev/dub_rt/CMakeFiles /Users/dev/dub_rt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dev/dub_rt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named audio_manipulation

# Build rule for target.
audio_manipulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 audio_manipulation
.PHONY : audio_manipulation

# fast build rule for target.
audio_manipulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/build
.PHONY : audio_manipulation/fast

#=============================================================================
# Target rules for targets named test_audio_manipulation

# Build rule for target.
test_audio_manipulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_audio_manipulation
.PHONY : test_audio_manipulation

# fast build rule for target.
test_audio_manipulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/build
.PHONY : test_audio_manipulation/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f extern/googletest/googlemock/CMakeFiles/gmock.dir/build.make extern/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f extern/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make extern/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f extern/googletest/googletest/CMakeFiles/gtest.dir/build.make extern/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f extern/googletest/googletest/CMakeFiles/gtest_main.dir/build.make extern/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/buffer_manager.o: src/buffer_manager.cpp.o
.PHONY : src/buffer_manager.o

# target to build an object file
src/buffer_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/buffer_manager.cpp.o
.PHONY : src/buffer_manager.cpp.o

src/buffer_manager.i: src/buffer_manager.cpp.i
.PHONY : src/buffer_manager.i

# target to preprocess a source file
src/buffer_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/buffer_manager.cpp.i
.PHONY : src/buffer_manager.cpp.i

src/buffer_manager.s: src/buffer_manager.cpp.s
.PHONY : src/buffer_manager.s

# target to generate assembly for a file
src/buffer_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/buffer_manager.cpp.s
.PHONY : src/buffer_manager.cpp.s

src/capture_module.o: src/capture_module.cpp.o
.PHONY : src/capture_module.o

# target to build an object file
src/capture_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/capture_module.cpp.o
.PHONY : src/capture_module.cpp.o

src/capture_module.i: src/capture_module.cpp.i
.PHONY : src/capture_module.i

# target to preprocess a source file
src/capture_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/capture_module.cpp.i
.PHONY : src/capture_module.cpp.i

src/capture_module.s: src/capture_module.cpp.s
.PHONY : src/capture_module.s

# target to generate assembly for a file
src/capture_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/capture_module.cpp.s
.PHONY : src/capture_module.cpp.s

src/decoder.o: src/decoder.cpp.o
.PHONY : src/decoder.o

# target to build an object file
src/decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/decoder.cpp.o
.PHONY : src/decoder.cpp.o

src/decoder.i: src/decoder.cpp.i
.PHONY : src/decoder.i

# target to preprocess a source file
src/decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/decoder.cpp.i
.PHONY : src/decoder.cpp.i

src/decoder.s: src/decoder.cpp.s
.PHONY : src/decoder.s

# target to generate assembly for a file
src/decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/decoder.cpp.s
.PHONY : src/decoder.cpp.s

src/encoder.o: src/encoder.cpp.o
.PHONY : src/encoder.o

# target to build an object file
src/encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/encoder.cpp.o
.PHONY : src/encoder.cpp.o

src/encoder.i: src/encoder.cpp.i
.PHONY : src/encoder.i

# target to preprocess a source file
src/encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/encoder.cpp.i
.PHONY : src/encoder.cpp.i

src/encoder.s: src/encoder.cpp.s
.PHONY : src/encoder.s

# target to generate assembly for a file
src/encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/encoder.cpp.s
.PHONY : src/encoder.cpp.s

src/ipc_manager.o: src/ipc_manager.cpp.o
.PHONY : src/ipc_manager.o

# target to build an object file
src/ipc_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/ipc_manager.cpp.o
.PHONY : src/ipc_manager.cpp.o

src/ipc_manager.i: src/ipc_manager.cpp.i
.PHONY : src/ipc_manager.i

# target to preprocess a source file
src/ipc_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/ipc_manager.cpp.i
.PHONY : src/ipc_manager.cpp.i

src/ipc_manager.s: src/ipc_manager.cpp.s
.PHONY : src/ipc_manager.s

# target to generate assembly for a file
src/ipc_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/ipc_manager.cpp.s
.PHONY : src/ipc_manager.cpp.s

src/output_module.o: src/output_module.cpp.o
.PHONY : src/output_module.o

# target to build an object file
src/output_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/output_module.cpp.o
.PHONY : src/output_module.cpp.o

src/output_module.i: src/output_module.cpp.i
.PHONY : src/output_module.i

# target to preprocess a source file
src/output_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/output_module.cpp.i
.PHONY : src/output_module.cpp.i

src/output_module.s: src/output_module.cpp.s
.PHONY : src/output_module.s

# target to generate assembly for a file
src/output_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/output_module.cpp.s
.PHONY : src/output_module.cpp.s

src/scheduler.o: src/scheduler.cpp.o
.PHONY : src/scheduler.o

# target to build an object file
src/scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/scheduler.cpp.o
.PHONY : src/scheduler.cpp.o

src/scheduler.i: src/scheduler.cpp.i
.PHONY : src/scheduler.i

# target to preprocess a source file
src/scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/scheduler.cpp.i
.PHONY : src/scheduler.cpp.i

src/scheduler.s: src/scheduler.cpp.s
.PHONY : src/scheduler.s

# target to generate assembly for a file
src/scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/scheduler.cpp.s
.PHONY : src/scheduler.cpp.s

src/speed_adjuster.o: src/speed_adjuster.cpp.o
.PHONY : src/speed_adjuster.o

# target to build an object file
src/speed_adjuster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/speed_adjuster.cpp.o
.PHONY : src/speed_adjuster.cpp.o

src/speed_adjuster.i: src/speed_adjuster.cpp.i
.PHONY : src/speed_adjuster.i

# target to preprocess a source file
src/speed_adjuster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/speed_adjuster.cpp.i
.PHONY : src/speed_adjuster.cpp.i

src/speed_adjuster.s: src/speed_adjuster.cpp.s
.PHONY : src/speed_adjuster.s

# target to generate assembly for a file
src/speed_adjuster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audio_manipulation.dir/build.make CMakeFiles/audio_manipulation.dir/src/speed_adjuster.cpp.s
.PHONY : src/speed_adjuster.cpp.s

tests/test_capture_module.o: tests/test_capture_module.cpp.o
.PHONY : tests/test_capture_module.o

# target to build an object file
tests/test_capture_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_capture_module.cpp.o
.PHONY : tests/test_capture_module.cpp.o

tests/test_capture_module.i: tests/test_capture_module.cpp.i
.PHONY : tests/test_capture_module.i

# target to preprocess a source file
tests/test_capture_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_capture_module.cpp.i
.PHONY : tests/test_capture_module.cpp.i

tests/test_capture_module.s: tests/test_capture_module.cpp.s
.PHONY : tests/test_capture_module.s

# target to generate assembly for a file
tests/test_capture_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_capture_module.cpp.s
.PHONY : tests/test_capture_module.cpp.s

tests/test_decoder.o: tests/test_decoder.cpp.o
.PHONY : tests/test_decoder.o

# target to build an object file
tests/test_decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_decoder.cpp.o
.PHONY : tests/test_decoder.cpp.o

tests/test_decoder.i: tests/test_decoder.cpp.i
.PHONY : tests/test_decoder.i

# target to preprocess a source file
tests/test_decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_decoder.cpp.i
.PHONY : tests/test_decoder.cpp.i

tests/test_decoder.s: tests/test_decoder.cpp.s
.PHONY : tests/test_decoder.s

# target to generate assembly for a file
tests/test_decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_decoder.cpp.s
.PHONY : tests/test_decoder.cpp.s

tests/test_encoder.o: tests/test_encoder.cpp.o
.PHONY : tests/test_encoder.o

# target to build an object file
tests/test_encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_encoder.cpp.o
.PHONY : tests/test_encoder.cpp.o

tests/test_encoder.i: tests/test_encoder.cpp.i
.PHONY : tests/test_encoder.i

# target to preprocess a source file
tests/test_encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_encoder.cpp.i
.PHONY : tests/test_encoder.cpp.i

tests/test_encoder.s: tests/test_encoder.cpp.s
.PHONY : tests/test_encoder.s

# target to generate assembly for a file
tests/test_encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_encoder.cpp.s
.PHONY : tests/test_encoder.cpp.s

tests/test_integration_level2.o: tests/test_integration_level2.cpp.o
.PHONY : tests/test_integration_level2.o

# target to build an object file
tests/test_integration_level2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_integration_level2.cpp.o
.PHONY : tests/test_integration_level2.cpp.o

tests/test_integration_level2.i: tests/test_integration_level2.cpp.i
.PHONY : tests/test_integration_level2.i

# target to preprocess a source file
tests/test_integration_level2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_integration_level2.cpp.i
.PHONY : tests/test_integration_level2.cpp.i

tests/test_integration_level2.s: tests/test_integration_level2.cpp.s
.PHONY : tests/test_integration_level2.s

# target to generate assembly for a file
tests/test_integration_level2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_integration_level2.cpp.s
.PHONY : tests/test_integration_level2.cpp.s

tests/test_output_module.o: tests/test_output_module.cpp.o
.PHONY : tests/test_output_module.o

# target to build an object file
tests/test_output_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_output_module.cpp.o
.PHONY : tests/test_output_module.cpp.o

tests/test_output_module.i: tests/test_output_module.cpp.i
.PHONY : tests/test_output_module.i

# target to preprocess a source file
tests/test_output_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_output_module.cpp.i
.PHONY : tests/test_output_module.cpp.i

tests/test_output_module.s: tests/test_output_module.cpp.s
.PHONY : tests/test_output_module.s

# target to generate assembly for a file
tests/test_output_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_audio_manipulation.dir/build.make CMakeFiles/test_audio_manipulation.dir/tests/test_output_module.cpp.s
.PHONY : tests/test_output_module.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... audio_manipulation"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... test_audio_manipulation"
	@echo "... src/buffer_manager.o"
	@echo "... src/buffer_manager.i"
	@echo "... src/buffer_manager.s"
	@echo "... src/capture_module.o"
	@echo "... src/capture_module.i"
	@echo "... src/capture_module.s"
	@echo "... src/decoder.o"
	@echo "... src/decoder.i"
	@echo "... src/decoder.s"
	@echo "... src/encoder.o"
	@echo "... src/encoder.i"
	@echo "... src/encoder.s"
	@echo "... src/ipc_manager.o"
	@echo "... src/ipc_manager.i"
	@echo "... src/ipc_manager.s"
	@echo "... src/output_module.o"
	@echo "... src/output_module.i"
	@echo "... src/output_module.s"
	@echo "... src/scheduler.o"
	@echo "... src/scheduler.i"
	@echo "... src/scheduler.s"
	@echo "... src/speed_adjuster.o"
	@echo "... src/speed_adjuster.i"
	@echo "... src/speed_adjuster.s"
	@echo "... tests/test_capture_module.o"
	@echo "... tests/test_capture_module.i"
	@echo "... tests/test_capture_module.s"
	@echo "... tests/test_decoder.o"
	@echo "... tests/test_decoder.i"
	@echo "... tests/test_decoder.s"
	@echo "... tests/test_encoder.o"
	@echo "... tests/test_encoder.i"
	@echo "... tests/test_encoder.s"
	@echo "... tests/test_integration_level2.o"
	@echo "... tests/test_integration_level2.i"
	@echo "... tests/test_integration_level2.s"
	@echo "... tests/test_output_module.o"
	@echo "... tests/test_output_module.i"
	@echo "... tests/test_output_module.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

