FROM ubuntu:22.04

# Instalar dependências
RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    build-essential \
    && apt-get clean

# Criar diretório de trabalho
WORKDIR /app

# Copiar arquivos do projeto
COPY IPCManager.h .
COPY Main.cpp .
COPY CMakeLists.txt .

# Compilar a aplicação
RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
    && cmake --build build --config Release

# Rodar a aplicação
CMD ["./build/IPCApp"]
